Lesson10_MbmStore_startup/MbmStore/Components/CartSummaryViewComponent.cs
using MbmStore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MbmStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Lesson10_MbmStore_startup/MbmStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using MbmStore.Infrastructure;
using MbmStore.Data;

namespace MbmStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private MbmStoreContext dataContext;

        public NavigationMenuViewComponent(MbmStoreContext dbContext)
        {
            dataContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(dataContext.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }
    }
}

Lesson10_MbmStore_startup/MbmStore/Controllers/CartController.cs
using MbmStore.Data;
using MbmStore.Infrastructure;
using MbmStore.Models;
using MbmStore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace MbmStore.Controllers
{
    public class CartController : Controller
    {

        private Cart cart;
        private MbmStoreContext dataContext;

        public CartController(Cart cartService, MbmStoreContext dbContext)
        {
            cart = cartService;
            dataContext = dbContext;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productID, string returnUrl)
        {
            Product product = dataContext.Products
            .FirstOrDefault(p => p.ProductId == productID);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productID, string returnUrl)
        {
            Product product = dataContext.Products
            .FirstOrDefault(p => p.ProductId == productID);
            if (product != null)
            {
               cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

Lesson10_MbmStore_startup/MbmStore/Views/Shared/_AddToCartButton.cshtml
@model MbmStore.Models.Product
@using MbmStore.Infrastructure

<div class="col-md-6">
    <form id="@Model.ProductId" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" name="ProductId" value="@Model.ProductId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

Lesson10_MbmStore_startup/MbmStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/css/*.min.css" />
    <link href="~/lib/bootstrap/css/custom.css" rel="stylesheet" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <title>MbmStore Catalogue</title>
</head>
<body class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">MusicBookMovie Store</a>
        <div class="col-4 text-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </nav>

    <div class="row panel">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Lesson10_MbmStore_startup/MbmStore/Views/Shared/_ProductSummaryBook.cshtml
@model MbmStore.Models.Book
@using MbmStore.Models;
<div class="row">
    <div class="col-md-2">
        <img src="~/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-4">
        <strong>Title:</strong> @Model.Title<br />
        <strong>Author:</strong> @Model.Author<br />
        <strong>Price:</strong> @Model.Price<br />
        <strong>Publisher:</strong> @Model.Publisher (@Model.Published)<br />
        <strong>ISBN:</strong> @Model.ISBN<br /> <br />
    </div>

    @await Html.PartialAsync("_AddToCartButton", (Product) Model)

</div>

Lesson10_MbmStore_startup/MbmStore/Views/Shared/_ProductSummaryMovie.cshtml
@model MbmStore.Models.Movie
@using MbmStore.Models

<div class="row">
    <div class="col-md-2">
        <img src="~/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-4">
        <strong>Title:</strong> @Model.Title<br />
        <strong>Director:</strong> @Model.Director<br>
        <strong>Price:</strong> @String.Format("{0:0.00}", Model.Price)
    </div>

    @await Html.PartialAsync("_AddToCartButton", (Movie) Model)
</div>

Lesson10_MbmStore_startup/MbmStore/Views/Shared/_ProductSummaryMusicCD.cshtml
@model MbmStore.Models.MusicCD
@using MbmStore.Models
<div class="row">
    <div class="col-md-2">
        <img src="~/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-4">
        <strong>Album:</strong> @Model.Title<br />
        <strong>Artist:</strong> @Model.Artist<br />
        <strong>Price:</strong> @Model.Price<br />
        <strong>Publisher:</strong> @Model.Label (@Model.Released)
    </div>

    @await Html.PartialAsync("_AddToCartButton", (Product) Model)

</div>